const level_end_x = 4050;

function initLevel1(){
    level1 = new Level(
        [   
            new Endboss(level_end_x),
            new Chicken(level_end_x),
            new Chicken(level_end_x),
            new Chicken(level_end_x),
            new Chicken(level_end_x),
            new Chicken(level_end_x),
            new Chicken(level_end_x),
            new SmallChicken(level_end_x),
            new SmallChicken(level_end_x),
            new SmallChicken(level_end_x),
            new SmallChicken(level_end_x),
            new SmallChicken(level_end_x),
            new SmallChicken(level_end_x),
        ],
        [
            new Cloud(level_end_x),
            new Cloud(level_end_x),
            new Cloud(level_end_x),
            new Cloud(level_end_x),
            new Cloud(level_end_x),
        ],
        [
            new BackgroundObject('./img/5_background/layers/air.png', -799), 
            new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', -799),
            new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', -799),
            new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', -799),
            new BackgroundObject('./img/5_background/layers/air.png', 0),
            new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 0),
            new BackgroundObject('./img/5_background/layers/air.png', 799),
            new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 799),
            new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 799),
            new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 799),
            new BackgroundObject('./img/5_background/layers/air.png', 799*2),
            new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 799*2),
            new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 799*2),
            new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 799*2),
            new BackgroundObject('./img/5_background/layers/air.png', 799*3),
            new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 799*3),
            new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 799*3),
            new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 799*3),
            new BackgroundObject('./img/5_background/layers/air.png', 799*4),
            new BackgroundObject('./img/5_background/layers/3_third_layer/1.png', 799*4),
            new BackgroundObject('./img/5_background/layers/2_second_layer/1.png', 799*4),
            new BackgroundObject('./img/5_background/layers/1_first_layer/1.png', 799*4),
            new BackgroundObject('./img/5_background/layers/air.png', 799*5),
            new BackgroundObject('./img/5_background/layers/3_third_layer/2.png', 799*5),
            new BackgroundObject('./img/5_background/layers/2_second_layer/2.png', 799*5),
            new BackgroundObject('./img/5_background/layers/1_first_layer/2.png', 799*5),
        ],
        [
            new Coin(level_end_x),
            new Coin(level_end_x),
            new Coin(level_end_x),
            new Coin(level_end_x),
            new Coin(level_end_x),
        ],
        [
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
            new Bottle(level_end_x),
        ],
        level_end_x
        );
}